### ISSUE TITLE
[FIX] 버그 잡기🐛

### ISSUE THREAD

**Issue by binisnil** [EAT-SSU/EatSSU-iOS#30]
## 목적

벌레를 잡기 위한 이슈입니다 ◠‿◠ 
버그 생길때마다 추가하기!

## 작업 상세 내용

- [ ] 별점 안누르고 텍스트 작성 화면으로 전환 시, 에러
- [ ] CustomNavigationBar 적용 안됨 현상 해결

**Comment by CJiu01** [comment]
열심히 잡아보세요 ◠‿◠
